### ISSUE TITLE
Supporting PyTorch 2.3

### ISSUE THREAD

**Issue by Kayaba-Akihiko** [fepegar/torchio#1179] opened 2024-06-16 16:03 UTC
PyTorch 2.3 would be forcibly replaced with PyTorch 2.2 when installing the latest TorchIO (0.19.7), breaking Torchvision installed.

**Comment by fepegar** [comment] 2024-06-16 19:58
Thanks for reporting this. Would it help to set an upper bound for
TorchVision as well?

**Comment by joshuacwnewton** [comment] 2024-06-17 16:45
Also, as a side effect of not supporting PyTorch 2.3, there is also an incompatibility with the recently released NumPy 2.0.0 (since `torch==2.2.x` now throws the following error):

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

Upgrading to PyTorch 2.3.1 fixes this issue.

**Comment by romainVala** [comment] 2024-06-18 06:10
Hi
@fepegar why did you add the incompatibility with torch 2.3
torch>=1.1,<2.3
I made a fresh new install a few weeks ago, and I am now working with torch 2.3.1 and torchio 0.19.6
it looks fine to me
any reported problem I missed ?

**Comment by BLQNXAY** [comment] 2024-06-21 06:16
I did test and torchio 0.19.6 does not force a change of pytorch version to 2.2, torchio 0.19.7 does appear to force a change of pytorch version causing trochvision to not work!

**Comment by fzimmermann89** [comment] 2024-06-28 08:06
Rel: #1178

**Comment by fepegar** [comment] 2024-06-28 18:33
Hi all. I tried to explain the problem in https://github.com/fepegar/torchio/pull/1178#issue-2353928409 but didn't do a very good job. I've just had a baby so I'm not sleeping very well :D and don't have much time.

This is what I wrote:

> This doesn't work
> 
> ```python
> import torch
> import torchio as tio
> 
> subject = tio.datasets.Colin27()
> subject.load()
> subjects = 10 * [subject]
> 
> from torch.utils.data import DataLoader
> loader = DataLoader(subjects, batch_size=4)
> batch = next(iter(loader))
> batch.__class__ is dict
> ```
> 
> because `batch` is an instance of `Subject`.
> 
> This happens in PyTorch >=2.3 because of
> 
> * [Preserve metadata for `MutableMapping` and `MutableSequence` in `pin_memory` and `collate_fn` pytorch/pytorch#120553](https://github.com/pytorch/pytorch/pull/120553)

The issue in that snippet is that `batch` is an instance of `Subject` which is **not** unexpected. We would typically (before PyTorch 2.3) expect a `dict` containing the same keys as the subject, and with 4D tensors instead of images.

Maybe these changes have caused this as well, but I haven't investigated (@c-winder):
- https://github.com/fepegar/torchio/issues/1181

@fzimmermann89, would you be able to take a look at this? The inheritance design of the `Subject` and its subclasses is not very elegant for historical reasons, so it might be tricky. @justusschock might be able to help as well, but I think he's a bit busy as well.

**Comment by fepegar** [comment] 2024-06-28 18:47
Here are the changes in the PyTorch commit that broke TorchIO: https://github.com/pytorch/pytorch/pull/120553/files#diff-ab54604ec520467537cb424daad0f56b2f5702e2f4d7fa2e9f68c9def296ccdf

**Comment by fzimmermann89** [comment] 2024-06-28 22:28
Mh, I am still a bit confused how torchio's datasets are supposed to be used (I only ever used the augmentations)

Currently, in torch 2.3 the batch is a subject.
And `subject['t1'].data` is the batched data tensor.

What you describe would be similar to setting
`torch.utils.data._utils.collate.default_collate_fn_map[tio.Subject] = lambda batch, _: {key: [subject[key].data for subject in batch] for key in batch[0]}`

This would result in batch being a normal dictionary c containing only the batched tensors.

Without a complete overhaul, I currently only solutions using a custom collate function.
Maybe somebody else has a good idea?

**Comment by fzimmermann89** [comment] 2024-06-28 22:29
...and congratulations 👶 :)

**Comment by fepegar** [comment] 2024-06-30 01:08
Thank you, @fzimmermann89!

> Mh, I am still a bit confused how torchio's datasets are supposed to be used (I only ever used the augmentations)

This isn't really related to datasets but to the `Subject` class implementation.

> Currently, in torch 2.3 the batch is a subject.
And subject['t1'].data is the batched data tensor.

Yes. This is not expected. The batch should be a dictionary.

```python
>>> import torch
>>> import torchio as tio
>>> from torch.utils.data import DataLoader

>>> subject = tio.Subject(image=tio.ScalarImage(tensor=torch.ones(1, 1, 1, 1)))
>>> subjects = 10 * [subject]

>>> loader = DataLoader(subjects, batch_size=2)
>>> batch = next(iter(loader))
```

Expected behavior (PyTorch < 2.3):

```python
>>> batch
{
    'image': {
        'data': tensor([[[[[1.]]]],



        [[[[1.]]]]]),
        'affine': tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]], dtype=torch.float64),
        'path': ['', ''],
        'stem': ['', ''],
        'type': ['intensity', 'intensity']
    }
}
>>> batch["image"]["data"].shape
torch.Size([2, 1, 1, 1, 1])
```

Unexpected behavior (PyTorch 2.3):

```python
>>> batch
Subject(Keys: ('image',); images: 1)
>>> batch["image"]["data"].shape
torch.Size([2, 1, 1, 1, 1])
```

The data is not lost with the new default collate function in PyTorch 2.3, but I find it confusing to have one subject with one image as that is not the case anymore, and it's definitely not what used to happen before, where the list of subjects was collated into a dictionary, and images were converted into tensors. Moreover, this subject now has 5D images, which is also unexpected in TorchIO.

I'm not sure how we can fix this with a minimal effect on users. I guess code won't break with the new changes in PyTorch and that is more important than having a batch of unexpected type? What do people think?

**Comment by rickymwalsh** [comment] 2024-07-02 23:16
Hi, 

The batch being of type Subject causes a problem when using PyTorch Lightning. I hope this is relevant here, let me know  if I should raise a separate issue or raise it in the Lightning repo.

The `apply_to_collection` function (and now `_apply_to_collection_slow`) is called when
moving the batch to GPU. This is applied recursively with the below code, where `data` is the batch 
(previously a `dict`, now of type `Subject`). [https://github.com/Lightning-AI/utilities/blob/main/src/lightning_utilities/core/apply_func.py#L84](https://github.com/Lightning-AI/utilities/blob/main/src/lightning_utilities/core/apply_func.py#L84)

```python
    elem_type = type(data)

    # Recursively apply to collection items
    if isinstance(data, Mapping):
        out = []
        for k, v in data.items():
            v = _apply_to_collection_slow(
                v,
                dtype,
                function,
                *args,
                wrong_dtype=wrong_dtype,
                include_none=include_none,
                allow_frozen=allow_frozen,
                **kwargs,
            )
            if include_none or v is not None:
                out.append((k, v))
        if isinstance(data, defaultdict):
            return elem_type(data.default_factory, OrderedDict(out))
        return elem_type(OrderedDict(out))
```

The problem comes at the last line, trying to re-apply the original type to the output, as Subject() isn't expecting
a dict as input, so we get the error:
`TypeError: The path argument cannot be a dictionary`



<details><summary>Full stacktrace: click to expand</summary>


```python
Traceback (most recent call last):
  File "/home/rwalsh/Documents/repos/pytorch_testing/pythonProject/mwe_lightning.py", line 63, in <module>
    run()
  File "/home/rwalsh/Documents/repos/pytorch_testing/pythonProject/mwe_lightning.py", line 59, in run
    trainer.fit(model, datamodule=dm)
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1030, in _run_stage
    self.fit_loop.run()
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 223, in advance
    batch = call._call_strategy_hook(trainer, "batch_to_device", batch, dataloader_idx=0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 311, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/strategies/strategy.py", line 277, in batch_to_device
    return model._apply_batch_transfer_handler(batch, device=device, dataloader_idx=dataloader_idx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 358, in _apply_batch_transfer_handler
    batch = self._call_batch_hook("transfer_batch_to_device", batch, device, dataloader_idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/core/module.py", line 347, in _call_batch_hook
    return trainer_method(trainer, hook_name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 159, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/pytorch_lightning/core/hooks.py", line 611, in transfer_batch_to_device
    return move_data_to_device(batch, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/lightning_fabric/utilities/apply_func.py", line 103, in move_data_to_device
    return apply_to_collection(batch, dtype=_TransferableDataType, function=batch_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 72, in apply_to_collection
    return _apply_to_collection_slow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 104, in _apply_to_collection_slow
    v = _apply_to_collection_slow(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/lightning_utilities/core/apply_func.py", line 118, in _apply_to_collection_slow
    return elem_type(OrderedDict(out))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/torchio/data/image.py", line 858, in __init__
    super().__init__(*args, **kwargs)
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/torchio/data/image.py", line 179, in __init__
    self.path = self._parse_path(path)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rwalsh/Documents/repos/pytorch_testing/env/lib/python3.11/site-packages/torchio/data/image.py", line 471, in _parse_path
    raise TypeError('The path argument cannot be a dictionary')
TypeError: The path argument cannot be a dictionary
```

</details>


### MWE

Expected behaviour: training completes without error.
Actual behaviour: error before training starts.

```bash
conda create -p ./venv python=3.11 pytorch=2.3.1 torchio=0.19.8 lightning=2.3.1 -c pytorch -c conda-forge
# No error with PyTorch<2.3
# conda create -p ./venv python=3.11 "pytorch<2.3" torchio=0.19.8 lightning=2.3.1 -c pytorch -c conda-forge
conda activate ./venv
```


```python
import torch
import torchio as tio
from pytorch_lightning import LightningModule, Trainer, LightningDataModule
from torch.utils.data import DataLoader


class ExampleDataModule(LightningDataModule):
    def setup(self, stage):
        subject = tio.datasets.Colin27()
        subject.load()
        self.subjects = 10 * [tio.Subject(subject)]

    def train_dataloader(self):
        return DataLoader(self.subjects, batch_size=2)

    def test_dataloader(self):
        return DataLoader(self.subjects, batch_size=2)


class SimpleModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.conv = torch.nn.Conv3d(1, 1, 1)

    def forward(self, x):
        return torch.sigmoid(self.conv(x))

    def training_step(self, batch, batch_idx):
        inputs = batch['t1'][tio.DATA]
        targets = batch['brain'][tio.DATA].float()
        pred = self(inputs)
        return torch.nn.functional.binary_cross_entropy(pred, targets)

    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=0.1)


def run():
    dm = ExampleDataModule()
    dm.prepare_data()
    dm.setup(stage="fit")

    model = SimpleModel()

    trainer = Trainer(num_sanity_val_steps=0, max_epochs=2, accelerator="cpu")
    trainer.fit(model, datamodule=dm)


if __name__ == '__main__':
    run()
```

**Comment by eigenvivek** [comment] 2024-07-24 15:16
Could we simply change the default function if the pytorch version is `>=2.3` (perhaps while also raising a warning for the user)?

E.g., we could add something like this to [`__init__.py`](https://github.com/fepegar/torchio/blob/3a81e25b39a1ad5fcc218ae3759c451a1722cfdd/src/torchio/__init__.py) (copying @fzimmermann89's function):

```python
if torch.__version__ >= "2.3":
    collate_fn = lambda batch, _: {key: [subject[key].data for subject in batch] for key in batch[0]}
    torch.utils.data._utils.collate.default_collate_fn_map[Subject] = collate_fn
```

Lots of cool updates are going into pytorch 2.3+ that would be super useful for packages that depend on pytorch/torchio, so hoping to find a solution to this version soft-lock!

**Comment by fzimmermann89** [comment] 2024-07-24 15:35
Shouldn't this approach also work for older pytorch versions, so maybe no version check is required..

**Comment by fepegar** [comment] 2024-07-24 21:16
I will revert the requirement, but we'll see errors and unexpected types in multiple applications that I'm not sure how will be fixed.

**Comment by c-winder** [comment] 2024-07-28 23:39
I think a new custom data loader class with a collate_fn that returns a dictionary might be the way to go. Something like this rough mockup?

```from typing import Any

import torch
import torch.utils.data
import torchio as tio


class SubjectDataLoader(torch.utils.data.DataLoader):

    def __init__(
            self,
            dataset: tio.data.SubjectsDataset,
            **kwargs
    ):

        super().__init__(
            dataset=dataset,
            collate_fn=self._collate,
            **kwargs
        )

    @staticmethod
    def _collate(batch_inputs: list[tio.Subject]) -> dict[str, Any]:

        # empty dict to store batch output
        batch_dict = dict()

        # iterate over the keys in the first subject
        for key, first_value in batch_inputs[0].items():

            # get list of the attribute values of each subject in the batch
            batch_attr_value = [batch_input[key] for batch_input in batch_inputs]

            # for image attrs we extract the tensors and stack to create a batched tensor
            if isinstance(first_value, tio.Image):
                batch_attr_value = [attr.data for attr in batch_attr_value]
                batch_attr_value = torch.stack(batch_attr_value, dim=0)

            # for tensor attrs we stack the tensors to create a batched tensor
            elif isinstance(first_value, torch.Tensor):
                batch_attr_value = torch.stack(batch_attr_value, dim=0)

            # update batch output
            batch_dict[key] = batch_attr_value

        return batch_dict


subject = tio.datasets.Colin27()
subject.load()
subjects = 10 * [subject]
subject_dataset = tio.data.SubjectsDataset(subjects)

loader = SubjectDataLoader(dataset=subject_dataset, batch_size=4)
batch = next(iter(loader))
assert batch.__class__ is dict
```

**Comment by c-winder** [comment] 2024-07-29 00:05
Alternatively, we can change`tio.SubjectsDataset.__getitem__` to return a dict. The best way is likely to add a method to `Subject` that returns a dict. This might be easier as it avoids creating a new class, but it would break existing code if people are relying on data loaders returning Subjects. I think I prefer the first option as it would be easier to tweak and extend. Here's another rough mockup:

```python
import copy
from typing import Any

import torch
import torch.utils.data
import torchio as tio


# quick mockup, subclass of Subject which I've added a new method to. Proper fix would add this to main Subject class
class Subject(tio.Subject):

    def __init__(self, *args, **kwargs: dict[str, Any]):
        super().__init__(*args, **kwargs)

    def to_dict(self) -> dict[str, Any]:
        # there's probably a cleaner way of doing this
        return {key: value for key, value in self.items()}


# as above, subclass of SubjectsDataset where I've overridden __getitem__.
class SubjectsDataset(tio.SubjectsDataset):
    def __init__(self, *args, **kwargs: dict[str, Any]):
        super().__init__(*args, **kwargs)

    def __getitem__(self, index: int):
        try:
            index = int(index)
        except (RuntimeError, TypeError):
            message = (
                f'Index "{index}" must be int or compatible dtype,'
                f' but an object of type "{type(index)}" was passed'
            )
            raise ValueError(message)

        subject = self._subjects[index]
        subject = copy.deepcopy(subject)  # cheap since images not loaded yet
        if self.load_getitem:
            subject.load()

        # Apply transform (this is usually the bottleneck)
        if self._transform is not None:
            subject = self._transform(subject)

        # Here I've changed the return to a dictionary rather than a Subject
        return subject.to_dict()


subject = tio.datasets.Colin27()
# convert to instance of temp subject class
subject = Subject(
    t1=subject['t1'],
    head=subject['head'],
    brain=subject['brain'],
)
subjects = 10 * [subject]
subject_dataset = SubjectsDataset(subjects)

loader = torch.utils.data.DataLoader(dataset=subject_dataset, batch_size=4)
batch = next(iter(loader))
assert batch.__class__ is dict
```

**Comment by romainVala** [comment] 2024-08-13 13:26
thanks @c-winder , 

I think that keeping Subject object from Dataloader may be convenient, so that you can use all functions of the class 

Your first proposition may be the way to go
I did not know on can redefine the `_collate`  function, this sound like a quite transparent solution.

**Comment by romainVala** [comment] 2024-09-17 15:55
Hi @c-winder 
while trying to solve this issue (#1189) I now better understand your solution

The main drawback I see is that now one get only the tensor data in the batch element of the dataloader

Ok this is most of the time the only need, but for regression task, it is convenient to add other field in subject (age and sex for instance) and then also get them in the dataloader batch iteration ...

as you can see in here (https://github.com/fepegar/torchio/issues/1189#issuecomment-2356281585) the old way
`     target = batch['t1'][tio.DATA]`
need to be replace (with your solution) by 
`     target = batch['t1']`

is there a generic way (with either solution) to get automatically a dict for batch['t1'] with the same keys as torchio.Subject()

**Comment by c-winder** [comment] 2024-09-17 16:24
Hi @romainVala

As far as I can see, the first solution works with both tensors and other objects. Tensors are stacked in the batch dimension, and other objects are simply combined into a list.

I'm not sure what you mean by "is there a generic way (with either solution) to get automatically a dict for batch['t1'] with the same keys as torchio.Subject()", in that example 't1' is a key of subject, and batch is a dictionary with the same keys as the subject. Let me know if I've misunderstood something, hopefully the example below helps.

```python
from typing import Any

import torch
import torch.utils.data
import torchio as tio


class SubjectDataLoader(torch.utils.data.DataLoader):

    def __init__(
            self,
            dataset: tio.data.SubjectsDataset,
            **kwargs
    ):

        super().__init__(
            dataset=dataset,
            collate_fn=self._collate,
            **kwargs
        )

    @staticmethod
    def _collate(batch_inputs: list[tio.Subject]) -> dict[str, Any]:

        # empty dict to store batch output
        batch_dict = dict()

        # iterate over the keys in the first subject
        for key, first_value in batch_inputs[0].items():

            # get list of the attribute values of each subject in the batch
            batch_attr_value = [batch_input[key] for batch_input in batch_inputs]

            # for image attrs we extract the tensors and stack to create a batched tensor
            if isinstance(first_value, tio.Image):
                batch_attr_value = [attr.data for attr in batch_attr_value]
                batch_attr_value = torch.stack(batch_attr_value, dim=0)

            # for tensor attrs we stack the tensors to create a batched tensor
            elif isinstance(first_value, torch.Tensor):
                batch_attr_value = torch.stack(batch_attr_value, dim=0)

            # update batch output
            batch_dict[key] = batch_attr_value

        return batch_dict


subject = tio.datasets.Colin27()
subject['age'] = 50
subject['sex'] = 'male'
subject.load()
subjects = 10 * [subject]
subject_dataset = tio.data.SubjectsDataset(subjects)

loader = SubjectDataLoader(dataset=subject_dataset, batch_size=4)
batch = next(iter(loader))
print(batch.keys())
print(batch['age'])
print(batch['sex'])
print(batch['t1'].shape)
```

This outputs:
 ```
dict_keys(['t1', 'head', 'brain', 'age', 'sex'])
[50, 50, 50, 50]
['male', 'male', 'male', 'male']
torch.Size([4, 1, 181, 217, 181])
```

**Comment by rickymwalsh** [comment] 2024-09-17 19:56
Hi @c-winder 

First of all, thanks for this fix! It helped me resolve my issue with Lightning.

I think part of @romainVala's point is on the other attributes contained within the tio.Image instances, usually you have 
attributes `data`, `affine` etc. and the above solution gives back just the `data` attribute. But as you point out, the most important attributes (e.g. age, sex, etc. will already be handled well if they were attributes of the Subject rather than the Image.

Here's a similar solution but, for tio.Image instances, creating a dict with stacked versions of each of the attributes:

```python
from typing import Any

import torch
import torch.utils.data
import torchio as tio
import numpy as np


def stack_(x):
    """ Determine the type of the input and stack it accordingly.
    Args:
        x: List of elements to stack
    Returns:
    	Stacked elements, as either a torch.Tensor, np.ndarray, dict (for tio.Image input) or list (e.g. list of strings)
    """
    if isinstance(x[0], torch.Tensor):
        return torch.stack(x, dim=0)
    elif isinstance(x[0], np.ndarray):
        return np.stack(x, axis=0)  # Maintain the original type, e.g. AFFINE is np.ndarray
    elif isinstance(x[0], tio.Image):
        # tio.Image is instance of dict containing attributes 'data', 'affine' etc. - stack these individually
        return {
            k: stack_([batch_im[k] for batch_im in x])
            for k in x[0].keys()
        }
    else:
        # Maintain a list of strings, for example
        return x


class SubjectDataLoader(torch.utils.data.DataLoader):

    def __init__(
            self,
            dataset: tio.data.SubjectsDataset,
            **kwargs
    ):
        super().__init__(
            dataset=dataset,
            collate_fn=self._collate,
            **kwargs
        )

    @staticmethod
    def _collate(batch_inputs: list[tio.Subject]) -> dict[str, Any]:

        batch_dict = {
            top_level_key: stack_([subject[top_level_key] for subject in batch_inputs])
            for top_level_key in batch_inputs[0].keys()
        }

        return batch_dict


subject = tio.datasets.Colin27()
subject['age'] = 50
subject['sex'] = 'male'
subject.load()
subjects = 10 * [subject]
subject_dataset = tio.data.SubjectsDataset(subjects)

loader = SubjectDataLoader(dataset=subject_dataset, batch_size=4)
batch = next(iter(loader))
print(batch.keys())
print(batch['age'])
print(batch['sex'])
print(batch['t1'][tio.DATA].shape)
print(batch['t1'][tio.AFFINE].shape)
print(batch['t1']['stem'])
```

Output:
```
dict_keys(['t1', 'head', 'brain', 'age', 'sex'])
[50, 50, 50, 50]
['male', 'male', 'male', 'male']
torch.Size([4, 1, 181, 217, 181])
(4, 4, 4)
['colin27_t1_tal_lin', 'colin27_t1_tal_lin', 'colin27_t1_tal_lin', 'colin27_t1_tal_lin']
```

**Comment by rousseau** [comment] 2024-09-18 06:44
@rickymwalsh
Considering longitudinal study (for instance), a subject may have different age attributes.
From this point of view, age should be related to images, not subject.

**Comment by romainVala** [comment] 2024-09-18 06:55
thanks @rickymwalsh and @c-winder 
I like the last solution since it gives the same behavior as before

@fepegar may be it worth to define this SubjectDataLoader class in torchio code so that everyone can easily use it ...

@rousseau , it is up to you to add an age attribute at the image level. (And the solution would work too)

```
subject['t1']['age'] = 45
subject['head']['age'] = 40
```

**Comment by fepegar** [comment] 2024-09-18 21:52
Thank you all for the discussion and the proposals!

@rickymwalsh, I discovered this issue because the CI for the notebook that uses Lightning [failed](https://github.com/fepegar/torchio-notebooks/actions/runs/9542698370/job/26297962261). 

I've opened a PR and requested some reviews from you:
- https://github.com/fepegar/torchio/pull/1194

**Closed** 2024-09-20 20:29 UTC
Labels: enhancement
