### ISSUE TITLE
Samplers and Queues supporting different number of sampled patches per each subject of the SubjectsDataset

### ISSUE THREAD

**Issue by snipdome** [fepegar/torchio#789] opened 2022-01-13 09:05 UTC
**🚀 Feature**
Samplers and Queues supporting different number of sampled patches per each subject of the SubjectsDataset

**Motivation**
In real case scenarios, the number of voxels of subjects may differ from each other. This may lead to torchio-users to want a different number of patches to be extracted from every subject volume. Right now, is only possible to have a fixed number of sampled patches for each subject.

**Additional context**
For CT and micro-CT volumes, subjects may have 100-10000 voxels in one of the three dimensions. Networks trained on such size need a patching system that should be able to support a great variety of volume sizes

**Comment by fepegar** [comment] 2022-01-19 15:11
Hi, @snipdome. I think this is a duplicate of
- #604
- #609 

Which I still need to address. We can follow the discussion in those. I'm going to close this for now. Feel free to reopen if I'm wrong.

**Closed by fepegar** 2022-01-19 15:11 UTC
Labels: enhancement
