### ISSUE TITLE
Support for applying intensity transforms to a subset of images in the Subject

### ISSUE THREAD

**Issue by dmus** [fepegar/torchio#359] opened 2020-11-22 15:04 UTC
**🚀 Feature**
At the moment an intensity transform is applied to all images of type intensity. There are use cases when a certain normalization/noise adding/clipping should only apply to some images in the subject

I was looking in the code and I think this feature could be achieved by changing the IntensityTransform to 

```python
from typing import Optional, List

from .transform import Transform
from .. import Image


class IntensityTransform(Transform):

    def __init__(
        self,
        images_to_apply: Optional[List[str]] = None,
        p: float = 1,
        copy: bool = True,
        keys: Optional[List[str]] = None,
    ):
        super().__init__(p=p, copy=copy, keys=keys)
        self.images_to_apply = images_to_apply

    """Transform that modifies voxel intensities only."""
    #@staticmethod
    def get_images(self, sample):

        images_dict = self.get_images_dict(sample)
        return list(images_dict.values())

        #return sample.get_images(intensity_only=True)

    #@staticmethod
    def get_images_dict(self, sample):
        images = {}
        for image_name, image in sample.items():
            if not isinstance(image, Image):
                continue
            if self.images_to_apply is not None and image_name not in self.images_to_apply:
                continue
            images[image_name] = image
        return images

        #return sample.get_images_dict(intensity_only=True)

```

Note the extra parameter `images_to_apply`. In this way all intensity transforms do only get the images they should transform. Is this the right way to approach this or am I missing something? 

When you agree with this approach I can try to make a pull request of it

**Comment by fepegar** [comment] 2020-11-22 15:27
Hi, @dmus. I think that makes sense. Thanks for the proposal. Can you share a specific use case?

I think your code looks good, but would that mean changing the docstrings and `__init__` methods of all transforms? That's what I did for the `keys` and `p` kwargs, but I feel like there must be more elegant solutions.

**Comment by dmus** [comment] 2020-11-23 08:25
Hi @fepegar , a use case is mri-based synthetic ct generation. Then the mri needs other preprocessing than the ct.

Yes, this suggestion would indeed mean changing the docstring and __init__ methods of all intensity transforms (all transforms that inherit from IntensityTransform). Another option is adding **kwargs to the constructor interface for all transforms, but I don't know if that is a more elegant solution

**Comment by romainVala** [comment] 2020-11-23 08:39
Hello
may be I misunderstood, but I though the transform argument keys was intended for this use (equivalent to images_to_apply) ...
no ?

**Comment by dmus** [comment] 2020-11-23 09:06
I thought that too when starting to use this library, but it turns out that the argument keys is only used when the input is a dictionary

**Comment by romainVala** [comment] 2020-11-23 09:24
you are right, and it is written is the doc ...

"        keys: Mandatory if the input is a Python dictionary. The transform will
            be applied only to the data in each key.
"

but having 2 separate attribute for the same use, it quite confusing

May be  keys and images_to_apply should be merged

**Comment by fepegar** [comment] 2020-11-23 09:55
I agree that those two could be merged. In #54 I suggest having both `include` and `exclude`. They would behave [like this](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.select_dtypes.html). I guess the images would be selected in a `get_images` method in `Transform`.

Adding these two kwargs would make it three that are common for all transforms (the other being the probability `p`). I don't know what's better:
1. Having all of them in all docstrings: explicit and clear, but more verbose and code duplication
2. Having **kwargs: more maintainable and less duplication, bad less explicit and obvious

Do you know any examples of how other libraries handle this?

**Comment by romainVala** [comment] 2020-11-23 10:23
Although I am not an expert, it seems that kwargs, is very common (in plotting functions, for instance https://seaborn.pydata.org/generated/seaborn.boxplot.html#seaborn.boxplot)

It make sense when the attributes are common to all transform, and then define in the parent class, and a correct link in the doc, make them explicit too ... (here they will be clearly define in transform.py)

I think the attribute p: (transform probabilities) could also be put in the kwargs ... since it is common to all transform

but I let you decide (of course)

**Comment by fepegar** [comment] 2020-11-23 10:28
Yes, I did check matplotlib earlier because I remember always being confused at the `**kwargs` at the end in my early days. But I suppose that if it's well documented, it should be fine. Because _of course, people always read documentation very carefully_ 😄.

We can work on this after #353 is merged.

**Comment by dmus** [comment] 2020-11-23 17:07
It would be nice indeed to have both an `include` and `exclude`. Do you think this should be selected in` Transform`? And then this should not be allowed for the spatial transforms, because then you get images with different affine matrices in one subject?

Having all arguments that a transform does not use directly (but the parent does use) passing via **kwargs seems like a good options

**Comment by fepegar** [comment] 2020-11-23 17:11
> Do you think this should be selected in Transform? And then this should not be allowed for the spatial transforms, because then you get images with different affine matrices in one subject?

I think if the user is explicitly specifying what should and should not be transformed, that should be the priority. I think the only thing that should be respected independently of those kwargs is that intensity transforms are not applied to images that are not `ScalarImage`.

**Comment by dmus** [comment] 2020-11-28 11:27
@fepegar What is the plan here? Or you planning to work on this or shall I create a pull request?

**Comment by fepegar** [comment] 2020-11-28 23:12
A PR sounds great. Have you thought about how to implement this? I can guide you through the process.

I'm thinking a way to go might be:
1. Replacing `p` by `**kwargs` in all transforms, pointing to the docs of `Transform`
2. Saving the values for `p`, `exclude` and `include` in `Transform`
3. Implement logic using `exclude` and `include` in `Subject.get_images` and `Subject.get_images_dict`
4. Use `exclude` and `include` from `IntensityTransform`, `SpatialTransform` and `Lambda` to get the right images
5. Write tests and docs

**Closed** 2020-12-07 10:32 UTC
Labels: enhancement
