### ISSUE TITLE
How to use sampler in dataset with different size

### ISSUE THREAD

**Issue by fishfishson** [fepegar/torchio#360] opened 2020-11-23 09:15 UTC
I use sampler following the tutorial and find that if images in dataset have different sizes, pytorch Dataloader will report size error for torch.stack() function. Can you help me to solve this problem?

**Comment by fepegar** [comment] 2020-11-23 09:44
Can you resize your images so that they have the same size? You can use `Resample` or `CropOrPad`.

**Comment by fepegar** [comment] 2020-11-23 10:04
It would help if you could share some code to reproduce the error.

**Comment by fishfishson** [comment] 2020-11-23 11:44
> It would help if you could share some code to reproduce the error.


    def get_dataset(
    	self,
    	mode,
    	patch_size=(64, 64, 64),
    	samples_per_volume=5,
    	max_queue_length=300):
    	if mode == 'train':
    		data = self.train_data
    	else:
    		data = self.val_data
    
        subjects = []
    
        for i in range(len(data)):
            img = tio.ScalarImage(data[i][0])
            gt = tio.LabelMap(data[i][1])
            subject = tio.Subject(
                img=img,
                gt=gt,
                prob_map=np.exp(gt.data)
            )
            subjects.append(subject)
        dataset = tio.SubjectsDataset(subjects)
    
        patchdataset = tio.Queue(
            subjects_dataset=dataset,
            max_length=max_queue_length,
            samples_per_volume=samples_per_volume,
            sampler=tio.sampler.UniformSampler(patch_size),
            num_workers=4,
            shuffle_subjects=True,
            shuffle_patches=True
        )

Here each img and gt have different shape sizes. 
When I apply DataLoader to  `patchdataset`, the python will report size error.

**Comment by fepegar** [comment] 2020-11-23 11:48
I see. In that, case you could either hard-code a shape using `transform = tio.CropOrPad(shape)` or use resampling to put the gt in the image space using `transform = tio.Resample('img')`. Then, you can instantiate your dataset as `dataset = tio.SubjectsDataset(subjects, transform=transform)`.

**Comment by fishfishson** [comment] 2020-11-23 12:05
> I see. In that, case you could either hard-code a shape using `transform = tio.CropOrPad(shape)` or use resampling to put the gt in the image space using `transform = tio.Resample('img')`. Then, you can instantiate your dataset as `dataset = tio.SubjectsDataset(subjects, transform=transform)`.

Thx for your suggestion. But actually, there exists a large size variation in my dataset. Crop and padding might influence the distribution of dataset a lot. Resizing is also harmful to the homogeneity of data. So currently the sampler does not support this kind of dataset right?

**Comment by fepegar** [comment] 2020-11-23 12:25
> Resizing is also harmful to the homogeneity of data.

What do you mean?

> So currently the sampler does not support this kind of dataset right?

I'm not sure the problem is in the sampler. Could you share your error traceback?

Here's an example of a subject whose img and gt have different sizes and that's fixed with `Resample` (thanks to @GReguig who implemented this):

```python
fpg.plot()
```

![Figure_1](https://user-images.githubusercontent.com/12688084/99961526-7fec6b00-2d86-11eb-90e3-6a23a6a51895.png)

```python
resampled = tio.Resample('t1')(fpg)
resampled.plot()
```

![Figure_2](https://user-images.githubusercontent.com/12688084/99961596-9b577600-2d86-11eb-86f4-c3d9ccce3540.png)

PS: code to generate the first image:

```python
import torchio as tio
fpg = tio.datasets.FPG()
fpg.seg.data[fpg.seg.data < 52] = 0
fpg.seg.data[fpg.seg.data > 53] = 0
cropped = tio.CropOrPad((100, 100, 100), mask_name='seg')(fpg)
fpg = tio.datasets.FPG()
fpg.seg = cropped.seg
```

**Comment by fishfishson** [comment] 2020-11-23 12:38
I'm sorry I didn't make it clear. I mean the space homogeneity like unifying the image spacing. 
The trace back is following:

```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-44c8047a8bdd> in <module>
      6 dataloader = DataLoader(dataset, batch_size=2)
      7 diter = iter(dataloader)
----> 8 diter.next()

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    383     def _next_data(self):
    384         index = self._next_index()  # may raise StopIteration
--> 385         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    386         if self._pin_memory:
    387             data = _utils.pin_memory.pin_memory(data)

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

~/miniconda3/envs/deepsdf/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     53             storage = elem.storage()._new_shared(numel)
     54             out = elem.new(storage)
---> 55         return torch.stack(batch, 0, out=out)
     56     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     57             and elem_type.__name__ != 'string_':

RuntimeError: stack expects each tensor to be equal size, but got [1, 291, 291, 101] at entry 0 and [1, 376, 376, 131] at entry 1
```
Here the dataset class is the same as patchdataset I mentioned above.

**Comment by fepegar** [comment] 2020-11-23 13:18
> Here the dataset class is the same as patchdataset I mentioned above.

Is it? It looks like this error is generated when trying to collate a `SubjectsDataset`.

```python
import torchio as tio
dataset = tio.SubjectsDataset((tio.datasets.Colin27(), tio.datasets.FPG()))
import torch
loader = torch.utils.data.DataLoader(dataset, batch_size=2)
next(iter(loader))
```

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-a4387374ec55> in <module>
----> 1 next(iter(loader))

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    361
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    401     def _next_data(self):
    402         index = self._next_index()  # may raise StopIteration
--> 403         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    404         if self._pin_memory:
    405             data = _utils.pin_memory.pin_memory(data)

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     45         else:
     46             data = self.dataset[possibly_batched_index]
---> 47         return self.collate_fn(data)

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py in <dictcomp>(.0)
     72         return batch
     73     elif isinstance(elem, container_abcs.Mapping):
---> 74         return {key: default_collate([d[key] for d in batch]) for key in elem}
     75     elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
     76         return elem_type(*(default_collate(samples) for samples in zip(*batch)))

/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py in default_collate(batch)
     53             storage = elem.storage()._new_shared(numel)
     54             out = elem.new(storage)
---> 55         return torch.stack(batch, 0, out=out)
     56     elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
     57             and elem_type.__name__ != 'string_':

RuntimeError: stack expects each tensor to be equal size, but got [1, 181, 217, 181] at entry 0 and [1, 256, 256, 176] at entry 1
```

If you were using the `Queue`, the error would have been raised by the `UniformSampler`:

```python
fpg = tio.datasets.FPG()
colin = tio.datasets.Colin27()
fpg['seg'] = colin.brain
sampler = tio.data.UniformSampler(32)
next(sampler(fpg))
```

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-abda2cc89634> in <module>
----> 1 next(sampler(fpg))

~/git/torchio/torchio/data/sampler/uniform.py in __call__(self, subject)
     20
     21     def __call__(self, subject: Subject) -> Generator[Subject, None, None]:
---> 22         subject.check_consistent_spatial_shape()
     23
     24         if np.any(self.patch_size > subject.spatial_shape):

~/git/torchio/torchio/data/subject.py in check_consistent_spatial_shape(self)
    143
    144     def check_consistent_spatial_shape(self) -> None:
--> 145         self.check_consistent_attribute('spatial_shape')
    146
    147     def check_consistent_orientation(self) -> None:

~/git/torchio/torchio/data/subject.py in check_consistent_attribute(self, attribute)
    140                 f'\n{pprint.pformat(values_dict)}'
    141             )
--> 142             raise RuntimeError(message)
    143
    144     def check_consistent_spatial_shape(self) -> None:

RuntimeError: More than one spatial_shape found in subject images:
{'seg': (181, 217, 181), 't1': (256, 256, 176)}
```

I'm still not sure why you don't think using `Resample` is a good idea.

**Comment by fishfishson** [comment] 2020-11-23 13:24
Thx. I will try resample.

**Comment by fepegar** [comment] 2020-11-23 13:26
Good! Closing this now. Feel free to reopen if you have more questions.

**Closed by fepegar** 2020-11-23 13:26 UTC
