### ISSUE TITLE
There is something wrong with the image origin

### ISSUE THREAD

**Issue by XiaoTianJianJun** [fepegar/torchio#1007] opened 2022-12-07 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

 When I read an image with torchio, the first two dimensions of the origin of the image are wrong
[image](https://www.dropbox.com/s/asspl6c2nsvvp8h/test.nii.gz?dl=0)
### Code for reproduction

```python
import torchio as tio
import SimpleITK as sitk

img_torch = tio.ScalarImage('./test.nii.gz')
img_itk = sitk.ReadImage('./test.nii.gz')

print('img_torch:{}'.format(img_torch.origin))
print('img_itk:{}'.format(img_itk.GetOrigin()))
```

### Actual outcome

Result of Simpleitk: (-213.51171875, -254.51171875, -1636.6500244140625)
Result of torchio: (213.51171875, 254.51171875, -1636.6500244140625)

I used a third-party library to test. Torchio's result is wrong

### Expected outcome

img_torch:(213.51171875, 254.51171875, -1636.6500244140625)
img_itk:(-213.51171875, -254.51171875, -1636.6500244140625)

### System info

```shell
Platform:   Linux-5.15.74.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
TorchIO:    0.18.83
PyTorch:    1.13.0+cu117
SimpleITK:  2.1.1.2 (ITK 5.2)
NumPy:      1.22.3
Python:     3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]
```

**Comment by romainVala** [comment] 2022-12-08 07:49
Hello
I do reproduce the same thing but I think nobody is wrong. It is just a matter of convention :
sitk use a lps convention and torchio a ras one, which mean that you will find a sign difference in the x and y coordinate

The reason is that torchio use both library stik and nibabel, which use those different conventions (respectively lps and ras).  So we need to pick one ... The only important thing is to  stay consistent with it

**Comment by dmus** [comment] 2022-12-08 12:54
Maybe nice if torchio can support both (and that you can specify via a global setting what you want for example). We had to make some code to convert from ras to lps

**Comment by XiaoTianJianJun** [comment] 2022-12-09 06:47
> Hello I do reproduce the same thing but I think nobody is wrong. It is just a matter of convention : sitk use a lps convention and torchio a ras one, which mean that you will find a sign difference in the x and y coordinate
> 
> The reason is that torchio use both library stik and nibabel, which use those different conventions (respectively lps and ras). So we need to pick one ... The only important thing is to stay consistent with it
Only xy is different and z is same. It looks strange

**Comment by fepegar** [comment] 2022-12-09 22:50
Hi, @XiaoTianJianJun. As @romainVala said, it's not wrong, just a different convention. There are multiple links in https://torchio.readthedocs.io/data/image.html#torchio.Image that you can use to learn more about the topic. I'm therefore closing this issue.

@dmus I'm not sure how we could implement that, and whether it'd be worth it. If you have ideas, we can open a discussion.

**Closed by fepegar** 2022-12-09 22:50 UTC
Labels: bug
