### ISSUE TITLE
Issue with deprecation

### ISSUE THREAD

**Issue by sarthakpati** [fepegar/torchio#484] opened 2021-03-12 15:28 UTC
Hey,

I am getting a very weird error when I have installed TorchIO on a new virtual environment:

```python-traceback
>>> import torchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/__init__.py", line 10, in <module>
    from .transforms import *  # noqa: F401, F403
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/transforms/__init__.py", line 1, in <module>
    from .transform import Transform
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/transforms/transform.py", line 13, in <module>
    from ..data.subject import Subject
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/data/__init__.py", line 1, in <module>
    from .queue import Queue
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/data/queue.py", line 9, in <module>
    from .subject import Subject
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/data/subject.py", line 8, in <module>
    from .image import Image
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/data/image.py", line 35, in <module>
    class Image(dict):
  File "/path/venv10.2/lib/python3.6/site-packages/torchio/data/image.py", line 190, in Image
    @deprecated(version='0.18.16', reason=deprecation_message)
TypeError: deprecated() got an unexpected keyword argument 'version'
```

When I comment out this line, it is all good. Wasn't sure if this was a bug or if I was doing something wrong. I installed using `pip install torchio` after creating using `conda create -p ./venv10.2 python=3.6 -y`.

**Comment by fepegar** [comment] 2021-03-12 15:41
Hi, @sarthakpati. I can't reproduce this. Do you think you can share one command to reproduce this? I'm using this and got no errors.

```shell
conda create -n dep python=3.6 ipython -y && conda activate dep && pip install torchio && python -c "import torchio"
```

**Comment by sarthakpati** [comment] 2021-03-12 15:51
Womp:

```bash
conda create -n dep python=3.6 ipython -y && conda activate dep && pip install torchio && python -c "import torchio"
Collecting package metadata (repodata.json): done
Solving environment: /
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults/linux-64::jedi-0.17.0-py36_0, defaults/noarch::parso-0.8.1-pyhd3eb1b0_0
  - defaults/linux-64::jedi-0.17.2-py36h06a4308_1, defaults/noarch::parso-0.7.0-pydone

## Package Plan ##

  environment location: /cbica/home/patis/.conda/envs/dep

  added / updated specs:
    - ipython
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backcall-0.2.0             |     pyhd3eb1b0_0          13 KB
    decorator-4.4.2            |     pyhd3eb1b0_0          12 KB
    jedi-0.17.0                |           py36_0         809 KB
    parso-0.8.1                |     pyhd3eb1b0_0          67 KB
    pygments-2.8.1             |     pyhd3eb1b0_0         737 KB
    ------------------------------------------------------------
                                           Total:         1.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  backcall           pkgs/main/noarch::backcall-0.2.0-pyhd3eb1b0_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.1.19-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py36h06a4308_0
  decorator          pkgs/main/noarch::decorator-4.4.2-pyhd3eb1b0_0
  ipython            pkgs/main/linux-64::ipython-7.16.1-py36h5ca1d4c_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  jedi               pkgs/main/linux-64::jedi-0.17.0-py36_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1j-h27cfd23_0
  parso              pkgs/main/noarch::parso-0.8.1-pyhd3eb1b0_0
  pexpect            pkgs/main/noarch::pexpect-4.8.0-pyhd3eb1b0_3
  pickleshare        pkgs/main/noarch::pickleshare-0.7.5-pyhd3eb1b0_1003
  pip                pkgs/main/linux-64::pip-21.0.1-py36h06a4308_0
  prompt-toolkit     pkgs/main/noarch::prompt-toolkit-3.0.8-py_0
  ptyprocess         pkgs/main/noarch::ptyprocess-0.7.0-pyhd3eb1b0_2
  pygments           pkgs/main/noarch::pygments-2.8.1-pyhd3eb1b0_0
  python             pkgs/main/linux-64::python-3.6.13-hdb3f193_0
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py36h06a4308_0
  six                pkgs/main/linux-64::six-1.15.0-py36h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  traitlets          pkgs/main/linux-64::traitlets-4.3.3-py36_0
  wcwidth            pkgs/main/noarch::wcwidth-0.2.5-py_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3



Downloading and Extracting Packages
backcall-0.2.0       | 13 KB     | ######################################################################################### | 100%
pygments-2.8.1       | 737 KB    | ######################################################################################### | 100%
jedi-0.17.0          | 809 KB    | ######################################################################################### | 100%
_libgcc_mutex-0.1    | 3 KB      | ######################################################################################### | 100%
parso-0.8.1          | 67 KB     | ######################################################################################### | 100%
decorator-4.4.2      | 12 KB     | ######################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dep
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting torchio
  Using cached torchio-0.18.29-py2.py3-none-any.whl (140 kB)
Collecting torch>=1.1
  Downloading torch-1.8.0-cp36-cp36m-manylinux1_x86_64.whl (735.5 MB)
     |████████████████████████████████| 735.5 MB 13 kB/s
Collecting Click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting scipy
  Using cached scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
Collecting numpy
  Using cached numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Requirement already satisfied: tqdm in /gpfs/fs001/cbica/home/patis/.local/lib/python3.6/site-packages (from torchio) (4.48.2)
Requirement already satisfied: SimpleITK<2 in /gpfs/fs001/cbica/home/patis/.local/lib/python3.6/site-packages (from torchio) (1.2.4)Collecting Deprecated
  Using cached Deprecated-1.2.11-py2.py3-none-any.whl (9.1 kB)
Requirement already satisfied: humanize in /gpfs/fs001/cbica/home/patis/.local/lib/python3.6/site-packages (from torchio) (2.5.0)
Collecting nibabel
  Using cached nibabel-3.2.1-py3-none-any.whl (3.3 MB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting dataclasses
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting wrapt<2,>=1.10
  Using cached wrapt-1.12.1-cp36-cp36m-linux_x86_64.whl
Collecting packaging>=14.3
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing, wrapt, typing-extensions, packaging, numpy, dataclasses, torch, scipy, nibabel, Deprecated, Click, torchio
Successfully installed Click-7.1.2 Deprecated-1.2.11 dataclasses-0.8 nibabel-3.2.1 numpy-1.19.5 packaging-20.9 pyparsing-2.4.7 scipy-1.5.4 torch-1.8.0 torchio-0.18.29 typing-extensions-3.7.4.3 wrapt-1.12.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/__init__.py", line 10, in <module>
    from .transforms import *  # noqa: F401, F403
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/transforms/__init__.py", line 1, in <module>
    from .transform import Transform
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/transforms/transform.py", line 13, in <module>
    from ..data.subject import Subject
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/data/__init__.py", line 1, in <module>
    from .queue import Queue
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/data/queue.py", line 9, in <module>
    from .subject import Subject
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/data/subject.py", line 8, in <module>
    from .image import Image
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/data/image.py", line 35, in <module>
    class Image(dict):
  File "/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages/torchio/data/image.py", line 190, in Image
    @deprecated(version='0.18.16', reason=deprecation_message)
TypeError: deprecated() got an unexpected keyword argument 'version'
```

I am on CentOS, BTW. Dunno if that makes a difference.

**Comment by fepegar** [comment] 2021-03-12 16:29
Thanks for trying that. Hmm, this is bizarre! I was going to ask about the version of `deprecated`, but we're getting the same one, `1.2.11`. Can you please confirm running this?

```shell
python -c "import deprecated; print(deprecated.__version__); print(deprecated.deprecated(version='1.2.3'))"
```

**Comment by sarthakpati** [comment] 2021-03-12 18:16
Here you go:

```bash
(dep) patis@/path>$ python -c "import deprecated; print(deprecated.__version__); print(deprecated.deprecated(version='1.2.3'))"
1.1.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: deprecated() got an unexpected keyword argument 'version'
```

**Comment by fepegar** [comment] 2021-03-12 18:34
It looks like that `python` is not the one from your environment, as your log says that `Deprecated-1.2.11` was installed, but that `python` is seeing `1.1.0`, therefore the error. Maybe you have misconfigured `PATH` in your `.bashrc`. Are you sure that is the newly installed Python? What is the output of `which python`?

**Comment by sarthakpati** [comment] 2021-03-12 18:44
Here you go:

```bash
(dep) patis@/path>$ which python
~/.conda/envs/dep/bin/python
```

**Comment by sarthakpati** [comment] 2021-03-12 18:47
This is weird:

```bash
(dep) patis@/path>$ which python
~/.conda/envs/dep/bin/python
(dep) patis@/path>$ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deprecated
>>> deprecated.__version__
'1.1.0'
>>> exit()
(dep) patis@/path>$ pip install deprecated
Requirement already satisfied: deprecated in /gpfs/fs001/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages (1.2.11)
Requirement already satisfied: wrapt<2,>=1.10 in /gpfs/fs001/cbica/home/patis/.conda/envs/dep/lib/python3.6/site-packages (from deprecated) (1.12.1)
```

**Comment by fepegar** [comment] 2021-03-20 15:05
I am going to close this issue, as it seems to be unrelated to TorchIO.

**Closed by fepegar** 2021-03-20 15:05 UTC

**Comment by sarthakpati** [comment] 2021-03-20 17:37
This is not present in the conda install, BTW...
