### ISSUE TITLE
Patch-based training on CPU gives an error regarding Queue.

### ISSUE THREAD

**Issue by heykeetae** [fepegar/torchio#125] opened 2020-04-19 21:20 UTC
I am training mri lesion segmentation task on a remote server without GPU, on which I am experimenting patch-based (using torchio.Queue()) data_loader with multiple CPU workers. Running through slightly modified codes from the provided colaboratory sample codes, I faced with the following error at the end of epoch 0 validation. Could you suggest a solution to this error?

[Update] Please note that **the same error occurs even with a single worker**.
```python
validation_loader = torch.utils.data.DataLoader(
    patches_validation_set, batch_size=validation_batch_size, num_workers=4)

training_loader = torch.utils.data.DataLoader(
    patches_training_set, batch_size=4, num_workers=4)
```

```python-traceback
-------------------------------------------
100%
4/4 [00:39<00:00, 9.80s/it]
tensor(0.9592)
tensor(0.9863)
tensor(0.9880)
tensor(0.9201)

Validation mean loss: 0.963
Starting epoch 1
0%
0/30 [00:05<?, ?it/s]

AssertionError                            Traceback (most recent call last)
<ipython-input-28-a2c6c63f5916> in <module>
      1 weights_stem = 'patch'
----> 2 train(num_epochs, training_loader, validation_loader, model, optimizer, weights_stem)

<ipython-input-12-09c63203945d> in train(num_epochs, training_loader, validation_loader, model, optimizer, weights_stem)
     74     for epoch_idx in range(1, num_epochs + 1):
     75         print('Starting epoch', epoch_idx)
---> 76         run_epoch(epoch_idx, Action.TRAIN, training_loader, model, optimizer)
     77         run_epoch(epoch_idx, Action.VALIDATE, validation_loader, model, optimizer)
     78         torch.save(model.state_dict(), f'{weights_stem}_epoch_{epoch_idx}.pth')

<ipython-input-12-09c63203945d> in run_epoch(epoch_idx, action, loader, model, optimizer)
     54     epoch_losses = []
     55     model.train(is_training)
---> 56     for batch_idx, batch in enumerate(tqdm(loader)):
     57         inputs, targets = prepare_batch(batch, device)
     58         optimizer.zero_grad()

~/anaconda3/envs/py3/lib/python3.7/site-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    216     def __iter__(self, *args, **kwargs):
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception
    220                 yield obj

~/anaconda3/envs/py3/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1117                 fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1118 
-> 1119         for obj in iterable:
   1120             yield obj
   1121             # Update and possibly print the progressbar.

~/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    343 
    344     def __next__(self):
--> 345         data = self._next_data()
    346         self._num_yielded += 1
    347         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    854             else:
    855                 del self._task_info[idx]
--> 856                 return self._process_data(data)
    857 
    858     def _try_put_index(self):

~/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
    879         self._try_put_index()
    880         if isinstance(data, ExceptionWrapper):
--> 881             data.reraise()
    882         return data
    883 

~/anaconda3/envs/py3/lib/python3.7/site-packages/torch/_utils.py in reraise(self)
    392             # (https://bugs.python.org/issue2651), so we work around it.
    393             msg = KeyErrorMessage(msg)
--> 394         raise self.exc_type(msg)

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/david/anaconda3/envs/py3/lib/python3.7/multiprocessing/queues.py", line 100, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torchio/data/queue.py", line 99, in __getitem__
    self.fill()
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torchio/data/queue.py", line 155, in fill
    subject_sample = self.get_next_subject_sample()
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torchio/data/queue.py", line 165, in get_next_subject_sample
    subject_sample = next(self.subjects_iterable)
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/david/anaconda3/envs/py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 769, in _try_get_data
    if self._workers_status[worker_id] and not w.is_alive():
  File "/home/david/anaconda3/envs/py3/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

**Comment by fepegar** [comment] 2020-04-20 09:42
Hi @heykeetae,

I can't reproduce. This seem like a PyTorch error. Have you tried with `num_workers=0` if you do `num_workers=1`, it still uses the multiprocessing logic (I think). Can you provide a minimal working example? Which version of PyTorch are you using?

It looks like other people have had this issue before:
- [AssertionError: can only join a child process](https://github.com/fastai/fastai/issues/1990)
- [Error while Multiprocessing in Dataloader
](https://discuss.pytorch.org/t/error-while-multiprocessing-in-dataloader/46845)

**Comment by fepegar** [comment] 2020-04-20 15:43
I'm going to close this as it seems unrelated to TorchIO. Feel free to reopen if you disagree.

**Closed by fepegar** 2020-04-20 15:43 UTC
