### ISSUE TITLE
Bug in colab notebook, TorchIO Getting Started tutorial

### ISSUE THREAD

**Issue by AyedSamy** [fepegar/torchio#868] opened 2022-05-03 10:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

In the TorchIO Getting Started tutorial (https://colab.research.google.com/github/fepegar/torchio-notebooks/blob/main/notebooks/TorchIO_tutorial.ipynb), I noticed a bug which seems due to the version of TorchIO.

Switching from TorchIO version: 0.18.57

to TorchIO version: 0.18.76, it fixed the issue

### Code for reproduction

In \## Training a network
\### Whole images
section
```python
one_batch = next(iter(training_loader))
```

### Actual outcome

A FileNotFoundError is produced

### Error messages

```python-traceback
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 157, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/collate.py", line 157, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/usr/local/lib/python3.7/dist-packages/torchio/data/image.py", line 641, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchio/data/image.py", line 156, in __init__
    self.path = self._parse_path(path)
  File "/usr/local/lib/python3.7/dist-packages/torchio/data/image.py", line 419, in _parse_path
    return [self._parse_single_path(p) for p in path]
  File "/usr/local/lib/python3.7/dist-packages/torchio/data/image.py", line 419, in <listcomp>
    return [self._parse_single_path(p) for p in path]
  File "/usr/local/lib/python3.7/dist-packages/torchio/data/image.py", line 409, in _parse_single_path
    raise FileNotFoundError(f'File not found: "{path}"')
FileNotFoundError: File not found: "data"
```

### Expected outcome

one batch loaded

**Comment by AyedSamy** [comment] 2022-05-03 13:42
2 in 1 bug report for this notebook  😁 , weights_url = 'https://github.com/fepegar/torchio-data/raw/master/models/whole_images_epoch_5.pth' in the train section has to be replaced by 'https://github.com/TorchIO-project/torchio-data/blob/main/models/whole_images_epoch_5.pth?raw=true', because the 1st url doesn't exist

**Comment by fepegar** [comment] 2022-05-09 21:53
Hi, @AyedSamy. Thanks for reporting. I'm trying to reproduce, but for some weird reason, I can't run the notebook. It says `/bin/bash: pip: command not found` when I simply try to run `!pip`. I'll try again tomorrow and open an issue on https://github.com/googlecolab/colabtools/issues if it's still not working.

**Comment by fepegar** [comment] 2022-05-09 21:56
It seems to be happy with `!pip3`, so I'll try that instead. Still not sure what's going on, though. `!pip` works for the transforms tutorial.

**Comment by fepegar** [comment] 2022-05-15 18:02
Can you please try again? I'm not getting any errors now.

**Comment by fepegar** [comment] 2022-05-15 18:18
I did get the errors for the URLs, which I am now fixing. Thanks for that!

**Comment by fepegar** [comment] 2022-05-15 18:21
URLs fixed in https://github.com/fepegar/torchio-notebooks/commit/9775c38899336d7f6609c2e26a5daff7606836f7

@all-contributors please add @AyedSamy for bug

**Closed** 2022-05-15 18:22 UTC
Labels: bug

**Comment by AyedSamy** [comment] 2022-05-15 21:06
It works perfect thanks for the update! 😁
