### ISSUE TITLE
patch-based learning 

### ISSUE THREAD

**Issue by 9B8DY6** [fepegar/torchio#327] opened 2020-10-07 08:30 UTC
during 'for batch in training_loader', I got a problem of underflow...
![image](https://user-images.githubusercontent.com/67573223/95306555-8308c600-08c2-11eb-94f8-0faf23911c75.png)
I think array/=array.max() had a problem like array.max is 0...but I don't know which array.max() is 0.
but I don't know why it happens!!!! Could it be in patch-based learning?

**Comment by fepegar** [comment] 2020-10-07 09:57
Hi, @9B8DY6.

This is a rare error and I can't reproduce. It looks like `array.max()` might be not 0 but really, really small. But it's hard to know without a working example. References:
- https://github.com/numpy/numpy/issues/9568
- https://github.com/mwshinn/PyDDM/pull/21

---

I'm going to close this for now. Feel free to reopen if you can help me reproduce. Please next time use the **Bug report** issue template and follow the instructions there. E.g., which versions of NumPy are you using? And of TorchIO?

**Closed by fepegar** 2020-10-07 09:57 UTC

**Comment by romainVala** [comment] 2020-10-07 12:48
Just as a note,
we also get this error, but only for some data, I could not find out why (I print the max, and it was always a few hundred, so no problem with the =/ ... very strange ) 
I can not reproduce now ...
 but if it happen you can also change line
https://github.com/fepegar/torchio/blob/3f98bcf00e4d004418f21f0cdb5282bee77fada3/torchio/transforms/transform.py#L99
 with np.errstate(all='warn'):

**Comment by fepegar** [comment] 2020-10-07 12:57
Thanks, @romainVala, that's good to know. It is indeed strange! I also thought of that line, but I introduced it to avoid silent warnings what would lead to bad errors: https://github.com/fepegar/torchio/issues/194#issuecomment-646729369

If this happens again, I will modify the NumPy error state within that line of `RescaleIntensity` as an exception.

**Comment by 9B8DY6** [comment] 2020-10-09 13:05
@romainVala I am making code on jupyter notebook so i don't know how to change that line on jupyter notebook... would you let me know how to do it...?

**Comment by fepegar** [comment] 2020-10-09 13:36
@9B8DY6 I recommend that you don't use Jupyter.

But for now, you can run

```python
!pip uninstal torchio -y
!git clone git@github.com:fepegar/torchio.git
!pip install -e ./torchio
```
And restart the notebook. Then you can edit the code in the repository you just cloned.
