### ISSUE TITLE
Incorrect batch size when transforms probability is smaller than one

### ISSUE THREAD

**Issue by NullConvergence** [fepegar/torchio#747] opened 2021-11-18 14:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug summary

When using a composition of transforms with different probabilities, the output size for batch is not symmetric.

### Code for reproduction

```python
all_trans = tio.Compose([
        tio.ToCanonical(),
        tio.Resample('volume'),
        tio.RandomAffine(p=0.2),
        tio.RandomElasticDeformation(p=0.1),
        tio.CropOrPad([100, 100, 100),
        tio.ZNormalization(include=['volume']),
    ])
```

### Actual outcome

The code returns a batch of elements with different sizes.

### Error messages

```python-traceback
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
```

### Expected outcome

A batch of elements with the same size.

**Comment by fepegar** [comment] 2021-11-18 14:09
Hi, @NullConvergence. Thanks for reporting. It's very difficult to figure out what's going on here because you have provided neither a reproducible example nor the full error log, nor the system information. All these were asked in the template you filled in.

I'm going to close this issue for now. Feel free to reopen if you are able to share the requested information.

**Closed by fepegar** 2021-11-18 14:09 UTC
Labels: bug
